const pricePlaneData = {
    yearly: [
        {
            userImage: "person3.jpg",
            pearks: [
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
            ]
        },
        {
            userImage: "person2.jpg",
            pearks: [
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
            ]
        },
        {
            userImage: "person1.jpg",
            pearks: [
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
            ]
        },
    ],
    monthly:[
        {
            userImage: "person1.jpg",
            pearks: [
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
            ]
        },
        {
            userImage: "person3.jpg",
            pearks: [
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
            ]
        },
        {
            userImage: "person2.jpg",
            pearks: [
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
                "Single User",
                "5GB Storage",
                "Unlimited Public Projects",
                "Community Access",
                "Unlimited Private Projects",
                "Dedicated Phone Support",
                "Free Subdomain",
                "Monthly Status Reports",
            ]
        },
    ],
}

export default pricePlaneData;