export const wishListData= [
    {
        logo:"image1.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"down",
            data:2.79
        },
        changePer:{
            dir:"down",
            data:"1.83"
        }
    },
    {
        logo:"image2.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"up",
            data:2.79
        },
        changePer:{
            dir:"up",
            data:"1.83"
        }
    },
    {
        logo:"image3.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"down",
            data:2.79
        },
        changePer:{
            dir:"down",
            data:"1.83"
        }
    },
    {
        logo:"image2.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"up",
            data:2.79
        },
        changePer:{
            dir:"up",
            data:"1.83"
        }
    },
    {
        logo:"image1.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"down",
            data:2.79
        },
        changePer:{
            dir:"down",
            data:"1.83"
        }
    },
    {
        logo:"image2.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"up",
            data:2.79
        },
        changePer:{
            dir:"up",
            data:"1.83"
        }
    },
    {
        logo:"image3.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"down",
            data:2.79
        },
        changePer:{
            dir:"down",
            data:"1.83"
        }
    },
    {
        logo:"image2.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"up",
            data:2.79
        },
        changePer:{
            dir:"up",
            data:"1.83"
        }
    },
    {
        logo:"image1.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"down",
            data:2.79
        },
        changePer:{
            dir:"down",
            data:"1.83"
        }
    },
    {
        logo:"image2.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"up",
            data:2.79
        },
        changePer:{
            dir:"up",
            data:"1.83"
        }
    },
    {
        logo:"image3.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"down",
            data:2.79
        },
        changePer:{
            dir:"down",
            data:"1.83"
        }
    },
    {
        logo:"image2.png",
        name:"Nasdaq",
        comName:"APPLE INC",
        marPrice:149.78,
        changeValue:{
            dir:"up",
            data:2.79
        },
        changePer:{
            dir:"up",
            data:"1.83"
        }
    },
]