const InvexRoutes = {
  Home: { path: '/' },
  LogIn: { path: '/logIn' },
  SignUp: { path: '/signUp' },
  Screener: { path: '/screener' },
  Market: { path: '/market' },
  Sectors: { path: '/sectors' },
  News: { path: '/news' },
  Price: { path: '/price' },
  Options: { path: '/options' },
  MacroEconomics: { path: '/macro-economics' },
  Resources: { path: '/resources' },
  Dashboard: { path: '/dashboard' },
  Symbol: { path: '/symbol' },
  BidTable: { path: '/bidtable' },
  CPIndex: { path: '/cpindex' },
  NonManufacture: { path: '/non_manufacture' },
  FinancialStatistics: { path: '/financial-statistics/:symbol' },
  FinancialShareInfo: { path: '/share-info/:symbol' },
  Financials: { path: '/financials/:symbol' },
  ValuationReport: { path: '/valuation-report' },
  Valuation: { path: '/valuation/:symbol' },
  SymbolOption: { path: '/symbol/option/:symbol' },
  SymbolNotPublished: { path: '/not-published' },
};

export default InvexRoutes;
